# Default state for all rules
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true

# Rules

# MD003/heading-style : Heading style : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md003.md
MD003:
  style: "atx"

# MD004/ul-style : Unordered list style : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md004.md
MD004:
  style: "sublist"

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013:
  line_length: 180
  code_blocks: false
  tables: false

MD045: false
